### ISSUE TITLE
[BUG] Cannot compile kernel modules

### ISSUE THREAD

**Issue by BigBoiMan123** [eupnea-linux/depthboot-builder#29]
**Describe the bug**
You cannot compile kernel modules because /lib/modules/5.10.131/build is not a directory, and instead appears to be a symlink leading to a directory that does not exist (/home/runner/work/kernel/kernel/chromeos-kernel).

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select Ubuntu as distro
3. Select KDE as desktop environment
4. Boot system
5. Install to internal storage
6. Attempt to compile a kernel module (I used WireGuard)

**Build system (please complete the following information):**
 - OS: Void Linux

**Additional context**

**Comment by Apacelus** [comment]
Should be fixed in https://github.com/eupnea-linux/kernel/commit/a818e8bc7f887afae7c91fd0d5a3c798d5935b3e
