### ISSUE TITLE
[FEATURE-REQUEST] Could i get iscsi_tcp support in the kernel

### ISSUE THREAD

**Issue by TobiasTheViking** [eupnea-linux/depthboot-builder#37]
I have an iscsi harddisk that i use to hold steam games. My chromebook runs said games (skyrim) fine, but doesn't have the disk space.

NFS is much much slower than iscsi, because of latency introduced by fetching a lot of small files.

Also, i don't feel the documentation has any real procedure for upgrading kernels. What is the procedure?

**Is your feature request related to a problem? Please describe.**
No problem, just optimization

**Describe the solution you'd like**
enable iscsi as modules

**Additional context**
Works better than nfs when getting a lot of small files.

**Comment by Apacelus** [comment]
Uhhh, I dunno... That module is not available on a generic linux kernel either:
```
$ sudo modprobe iscsi
modprobe: FATAL: Module iscsi not found in directory /lib/modules/5.19.0-76051900-generic
```

**Comment by Apacelus** [comment]
Ill add manual building to the kernel script later, so anyone can build kernels

**Comment by Apacelus** [comment]
The docs will be rewritten very soon

**Comment by TobiasTheViking** [comment]
Very much appreciated. :)

**Comment by Apacelus** [comment]
The instructions on how to build a kernel can be found [here](https://eupnea-linux.github.io/docs.html#/build-pages/build-kernel)
