### ISSUE TITLE
[FEATURE-REQUEST] Ability to boot over UEFI

### ISSUE THREAD

**Issue by iu0v1** [eupnea-linux/depthboot-builder#55]
When I try to boot any generated image on samsung chromebook plus v2 (nautilus) with mrchromebox uefi firmware - everything immediately ends at boot error `No bootfile found for UEFI! Mybe the image does not support X64 UEFI!`.

I assume that images work only in legacy bios mode. If so, would it be possible to add some additional image generation option that would add the ability to load in uefi mode?

**Comment by joebobbio** [comment]
Just use regular Linux

**Comment by iu0v1** [comment]
> Just use regular Linux

The idea behind using this particular one is to make sure at what stage the sound problem occurs, the audio does not work on any mainline Linux dist. The scripts from eupnea-linux/audio-scripts also do not produce any results. So I wanted to make sure that I wasn't "cooking" them incorrectly, and look at some ready-made solution.

**Comment by WeirdTreeThing** [comment]
If you are having issues with audio make an issue on that repo instead.

**Comment by Apacelus** [comment]
@iu0v1 this whole Project is about running Linux on Chromebooks with stock firmware. Our slogan is literally:
> Boot a full Linux system and gain complete control over your device WITHOUT modifying the firmware. 

Depthboot is nothing more than a stock base system with a few configs and a special layout. There is no magic. 

If you have an issue with the audio script (which is UEFI/RW_L compatible) make an issue there.

**Comment by iu0v1** [comment]
@Apacelus gotcha, I will do so. Thank you.

**Comment by paulmcauley** [comment]
I use the Mr. Chromebox coreboot firmware and would also request this feature.  Mainly because I would like to use the audio scripts and modified kernels to make audio work, and I also don't want the ChromeOS firmware as it requires faff before you boot and remember it reverting from whatever mode was required to boot standard Linux.

**Comment by joebobbio** [comment]
the [audio scripts](https://github.com/WeirdTreeThing/chromebook-linux-audio) work just fine on regular Linux

**Comment by paulmcauley** [comment]
> the [audio scripts](https://github.com/WeirdTreeThing/chromebook-linux-audio) work just fine on regular Linux

Installing custom kernels for audio is not so simple as it could be with an automated installer.
