### ISSUE TITLE
[BUG] not able to build on crouton

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#58]
**Describe the bug**

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select arch as distro
3. Select gnome as desktop environment
4. wait for installation.

**Full log**

Verbose log:
(sid)test@localhost:~/depthboot-builder/depthboot-builder$ git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder && cd depthboot-builder && ./main.py 
Cloning into 'depthboot-builder'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 46 (delta 1), reused 22 (delta 0), pack-reused 0
Receiving objects: 100% (46/46), 53.98 KiB | 3.37 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Dependencies already installed, skipping
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux image.
You can press Ctrl+C at any time to stop the script.
Select the default options if you are unsure.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Fedora ~2.1GB (recommended)
   Ubuntu ~3.7GB
   Pop!_OS 8.1GB
 > Arch 3.0GB
arch latest selected
Which desktop environment (Desktop GUI) would you like to use?
 > Gnome (recommended) +5.4GB
   KDE (recommended) +5.1GB
   Xfce (recommended for weak devices) +4.1GB
   LXQt (recommended for weak devices) +4.5GB
   budgie +4.7GB
   cli +0GB
Gnome selected
Enter a username for the new user
Username (default: 'localuser'): corn
Using corn as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > Mainline (default, recommended)
   ChromeOS (recommended for some devices)
Mainline kernel selected
User input complete
Not enough space in /tmp to build image. At least 13GB is required
Remount /tmp to increase its size? (Y/n)
y 
Increasing size of /tmp
Size of /tmp increased
Namespace(local_path=None, device_override=None, device_selection=False, verbose=False, download_progress=False, no_shrink=False, verbose_kernel=False, skip_size_check=False, image_size=[10], dev_build=False, skip_commit_check=False)
Starting build
Cleaning + preparing host system
Creating mount points
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading mainline kernel
Downloading: 13mb / 14mb
Downloading latest arch rootfs from geo.mirror.pkgbuild.com
Downloading: 159mb / 159mb
Preparing image
Mounting empty image
Preparing device/image partition
Flashing kernel to device/image
28176+0 records in
28176+0 records out
14426112 bytes (14 MB, 14 MiB) copied, 0.259089 s, 55.7 MB/s
28176+0 records in
28176+0 records out
14426112 bytes (14 MB, 14 MiB) copied, 0.27578 s, 52.3 MB/s
Formatting rootfs part
mke2fs 1.47.0 (5-Feb-2023)
Device/image preparation complete
Extracting rootfs
Extracting arch rootfs
 159MiB 0:00:06 [26.0MiB/s] [================================================================================>] 100%            

Rootfs extraction complete
Applying distro agnostic configuration
Fixing screen rotation
Cleaning /boot
Configuring user
/bin/sh: 1: file: not found
Distro agnostic configuration complete
Configuring Arch
Preparing pacman
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/4E048FEE60564A51F29F98FF093BE77FED52EC57.rev'
gpg: Done
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
/usr/sbin/pacman-key: line 194: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 194: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 194: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 194: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 194: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
/usr/sbin/pacman-key: line 207: /dev/fd/63: No such file or directory
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:  95  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  72  signed:  27  trust: 72-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-07-12
gpg: next trustdb check due at 2023-07-12
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  95  trust: 1-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  72  signed:  27  trust: 72-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-07-12
*** closefrom failed to close a file descriptor ***: terminated
*** closefrom failed to close a file descriptor ***: terminated
*** closefrom failed to close a file descriptor ***: terminated
error: GPGME error: Invalid crypto engine
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
Traceback (most recent call last):
  File "/home/test/depthboot-builder/depthboot-builder/depthboot-builder/./main.py", line 243, in <module>
    build.start_build(build_options=user_input, args=args)
  File "/home/test/depthboot-builder/depthboot-builder/depthboot-builder/build.py", line 413, in start_build
    distro.config(build_options["de_name"], build_options["distro_version"], verbose, build_options["kernel_type"])
  File "/home/test/depthboot-builder/depthboot-builder/depthboot-builder/distro/arch.py", line 35, in config
    chroot("pacman -Syyu --noconfirm")  # update the whole system
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/depthboot-builder/depthboot-builder/depthboot-builder/functions.py", line 126, in chroot
    return bash(f'chroot /mnt/depthboot /bin/bash -c "{command}"')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/depthboot-builder/depthboot-builder/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'chroot /mnt/depthboot /bin/bash -c "pacman -Syyu --noconfirm"' returned non-zero exit status 1.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
(sid)test@localhost:~/depthboot-builder/depthboot-builder/depthboot-builder$ 

**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
Crouton on samsung chromebook 4 running debian sid chroot
**Additional context
not able to set previleged container on crostini on octopus device

**Comment by Apacelus** [comment]
> *** closefrom failed to close a file descriptor ***: terminated
*** closefrom failed to close a file descriptor ***: terminated
*** closefrom failed to close a file descriptor ***: terminated
error: GPGME error: Invalid crypto engine
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

Try restarting the script. Doesnt seem like its our fault here.

**Comment by cornflakes6374** [comment]
> > *** closefrom failed to close a file descriptor ***: terminated
> > *** closefrom failed to close a file descriptor ***: terminated
> > *** closefrom failed to close a file descriptor ***: terminated
> > error: GPGME error: Invalid crypto engine
> > error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
> 
> Try restarting the script. Doesnt seem like its our fault here.

i did restarted the script and its doing the same message

**Comment by cornflakes6374** [comment]
im gonna try in a different crouton chroot, i will tell the results when im done

**Comment by Apacelus** [comment]
Yeah, it seems this may be due to the script not mounting /dev. We'll test a bit and push a fix soon

**Comment by cornflakes6374** [comment]
tried in kinetic chroot and nope still not working, guess i will wait for the fix
![Screenshot 2023-04-08 2 02 21 PM](https://user-images.githubusercontent.com/116115140/230736291-8681fa6a-a8c8-4ab5-b9eb-6cd494b5b0d5.png)

**Comment by cornflakes6374** [comment]
ok i built it successfully in onworks but how do i get the file from onworks so i can download it to my chromebook?

**Comment by Apacelus** [comment]
Alright, ff301cbca6d7bb7f662ffa97cb9780b6aec0f4de should fix the issues with non-mounted dirs
