### ISSUE TITLE
[FEATURE-REQUEST] More Distros?

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#64]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to add more distros like gentoo (i know [chromeos is already based on gentoo](https://wiki.gentoo.org/wiki/ChromeOS) but try to add gentoo distro) , linux mint (ubuntu based) manjaro (arch based) and Alpine Linux
**Additional context**

**Comment by Apacelus** [comment]
These are my reasons for not writing the code, I am **NOT** saying I wont look into PRs for these distros. So if you (or someone else) want to make a PR for these distros, you are very welcome.
Also, [generic iso support](https://github.com/orgs/eupnea-linux/projects/4?pane=issue&itemId=13131058) for systemd systems is planned.

1. Gentoo: Arch is already a distro that doesnt like to be "pre-installed" and Gentoo even more so. If someone would want to use Gentoo, they would install it themselves, as such users usually have enough knowledge to do so.
2. Linux mint: We already have 2 Ubuntu distros and we plan to add support for Linux Mint's DEs.
3. Manjaro: [manjarno.snorlax.sh](https://manjarno.snorlax.sh/). 
4. Alpine: No systemd + differnt packaging format (apk, not to be confused with apk) -> would need a new repo.

**Comment by Apacelus** [comment]
I've just added generic ISO support for those that wish to use other distros

**Comment by cornflakes6374** [comment]
ok, i will test it out with gentoo, (probably will not work as it uses openrc, but i will try, if not working, i will try debian and manjaro)

**Comment by cornflakes6374** [comment]
none of them worked, some say squashfs not found, one worked but it said /bin/bash no such file or directory so i guess the feature is currently unstable and unsupported for now

**Comment by Apacelus** [comment]
gentoo and manjaro will work now (although manjaro will not boot into a gui). Debian seems to be a pure initrd installer, so it will not work.

You can debootstrap a debian rootfs and give it to depthboot builder when it prompts for that
