### ISSUE TITLE
[BUG] Right Click doesn't work in KDE (all distros that have this DE)

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#66]
**Describe the bug**
Right clicking by pressing 2 fingers on the touchpad does not work on KDE

**To Reproduce**
Press 2 fingers on the touchpad

**Full log**

Verbose log:

**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
Crouton on Samsung chromebook 4 (casta)
**Additional context**

**Comment by Apacelus** [comment]
This is the default behavior of some DEs, for example GNOME has it too (except on PopOS where it is turned on ootb).

As per our [necessary-only modding policy](https://eupnea-linux.github.io/faq#are-the-depthboot-distros-modified) I will not change that.

**Comment by cornflakes6374** [comment]
just realized that i had to press the bottom right corner of the touchpad to right click, not by touching 2 fingers.
