### ISSUE TITLE
Depthboot Builder freezes whole computer when creating Pop!OS image with Eupnea Kernel

### ISSUE THREAD

**Issue by HyperrGB** [eupnea-linux/depthboot-builder#70]
**Describe the bug**
I run the Builder and it gets up to the part where it combines the things downloaded. Then freezes.

**Gemini Lake Asus C204**

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select Pop!os as distro

**Build system (please complete the following information):**
 - OS: Fedora running on Legacy Boot

**Comment by Apacelus** [comment]
1. Very descriptive issue name
2. Can I get a full log of the build

**Comment by HyperrGB** [comment]
> 1. Very descriptive issue name
> Sorry, Depthboot Freezes on run
> 2. Can I get a full log of the build
> How can I get a log? My screen freezes then I have to shutdown. I left it for 30 minutes when it was frozen but when I came back it was still frozen.

**Comment by Apacelus** [comment]
Run again with -v, then take a screenphoto (with your phone) when its frozen

**Comment by Apacelus** [comment]
Issue must be distro/device performance specific, as the github runner had no issues building popos

https://github.com/eupnea-linux/depthboot-builder/actions/runs/4861627374/jobs/8666894804#step:5:582
