### ISSUE TITLE
[FEATURE-REQUEST] Non-Interactive build mode for CI environments

### ISSUE THREAD

**Issue by mikedolx** [eupnea-linux/depthboot-builder#72]
**Is your feature request related to a problem? Please describe.**
The current build script requires me to do interactively choose my build configuration, which is nice and convinient if want to make a single build. BUT ...

**Describe the solution you'd like**
... I would like to build the image using my own build server with GitLab and CI. A gitlab-runner, which is installed on the build-vm would then execute a small script, that triggers a build for a specific configuration. 
Is this feature already there and i just need to modify some config files?

**Comment by Apacelus** [comment]
Have a look at https://github.com/eupnea-linux/depthboot-builder/blob/main/.github/workflows/test-builds.yml

I do not want to implement a non-interactive mode into the script directly as the current setup of directly "hooking" into the build.py file works well enough for me.

**Comment by mikedolx** [comment]
Thanks a lot, that should do it 👍
