### ISSUE TITLE
[FEATURE-REQUEST] Get rid of OS verification is off screen

### ISSUE THREAD

**Issue by apandada1** [eupnea-linux/depthboot-builder#73]
**Is your feature request related to a problem? Please describe.**
I installed Arch Linux to the internal storage using the `install-to-internal` command.

Everytime I turn on the computer, I have to press `ctrl + d` to boot Arch.

Is there a way to bypass this screen so that I would not have to press `ctrl+d`, and the computer will automatically boot to Linux?

**Describe the solution you'd like**
I want the computer to automatically boot Linux.

**Additional context**
I don't know of pressing the space bar to turn OS verification on will be safe here.

![IMG_20230506_165752](https://user-images.githubusercontent.com/3063132/236646434-ce5da72b-554b-4f59-9d7e-0a69087e8f67.jpg)

**Comment by Apacelus** [comment]
Not unless you install MrChromebox UEFI (not rw_l), but then you wouldnt need Depthboot

**Comment by WeirdTreeThing** [comment]
Easy, just compile coreboot with a linux payload built in. You are able to bypass any boot message and get straight to the linux goodness.

**Comment by apandada1** [comment]
I tried a few distros from rw_l, and touch does not work (sound works after installing the audio script). However, touch works perfectly with depthboot and the chromeos kernel (sound works after installing the audio script).

I have a HP x360 14a (Blooguard)

If I install MrChromebox UEFI, do you think touchscreen will work out of the box with the default kernel in distros like Ubuntu/Arch?

I am hesitant to install the full UEFI because I am unsure if touch will work there.

**Comment by apandada1** [comment]
> Easy, just compile coreboot with a linux payload built in. You are able to bypass any boot message and get straight to the linux goodness.

Is there a guide for doing that?

**Comment by Apacelus** [comment]
> If I install MrChromebox UEFI, do you think touchscreen will work out of the box with the default kernel in distros like Ubuntu/Arch?

Ask the Chrultrabook community

**Comment by WeirdTreeThing** [comment]
>If I install MrChromebox UEFI, do you think touchscreen will work out of the box with the default kernel in distros like Ubuntu/Arch?

Yes it will.

> Is there a guide for doing that?

That was sarcasm.

**Comment by apandada1** [comment]
Thanks for the information, and thanks for maintaining this great project.
