### ISSUE TITLE
How to edit the kernel parameters?

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#75]
i want to edit the kernel parameters, but there is no grub or something there, which means it can only be edited in a bootloader and not the system. so how do i edit the kernel parameters?

**Comment by Apacelus** [comment]
run `modify-cmdline` from a booted depthboot system

**Comment by cornflakes6374** [comment]
> run `modify-cmdline` from a booted depthboot system

a python error shows at the end of the command, is that normal?
`[corn@casta ~]$ modify-cmdline

*```
* (gedit:2829): WARNING **: 10:51:46.789: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


(gedit:2829): dconf-WARNING **: 10:51:46.790: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code8: Failed to create file “/home/corn/.config/dconf/user.Q44A41”: Read-only file system

** (gedit:2829): WARNING **: 10:51:46.790: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.791: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


(gedit:2829): dconf-WARNING **: 10:51:46.792: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code8: Failed to create file “/home/corn/.config/dconf/user.QH9A41”: Read-only file system

** (gedit:2829): WARNING **: 10:51:46.792: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.794: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.795: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.795: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.796: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.796: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (gedit:2829): WARNING **: 10:51:46.796: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory


(gedit:2829): Gtk-WARNING **: 10:51:47.088: Attempting to store changes into '/home/corn/.local/share/recently-used.xbel', but failed: Failed to create file “/home/corn/.local/share/recently-used.xbel.093S41”: Read-only file system

(gedit:2829): Gtk-WARNING **: 10:51:47.088: Attempting to set the permissions of '/home/corn/.local/share/recently-used.xbel', but failed: Read-only file system

(gedit:2829): dconf-WARNING **: 10:52:26.183: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code8: Failed to create file “/home/corn/.config/dconf/user.FUQT41”: Read-only file system

** (gedit:2829): WARNING **: 10:52:26.207: Could not create config directory


(gedit:2829): Gtk-WARNING **: 10:52:26.208: Attempting to store changes into '/home/corn/.local/share/recently-used.xbel', but failed: Failed to create file “/home/corn/.local/share/recently-used.xbel.PWDW41”: Read-only file system

(gedit:2829): Gtk-WARNING **: 10:52:26.208: Attempting to set the permissions of '/home/corn/.local/share/recently-used.xbel', but failed: Read-only file system

(gedit:2829): tepl-WARNING **: 10:52:26.208: Failed to save metadata: Error creating directory /home/corn/.local/share/gedit: Read-only file system

New cmdline:
console= root=PARTUUID=bf39011e-ad94-4d63-bda2-cc934cf2ce3b i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1
Press ENTER to continue or CTRL+C to cancel    
Backing up kernel
Backing up kernel requires root privileges.
[sudo] password for corn: 
131072+0 records in
131072+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 14.6608 s, 4.6 MB/s
Installing new kernel
Installing kernel requires root privileges.
131072+0 records in
131072+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.810585 s, 82.8 MB/s
78608+0 records in
78608+0 records out
40247296 bytes (40 MB, 38 MiB) copied, 9.22803 s, 4.4 MB/s
Traceback (most recent call last):
  File "/usr/lib/eupnea/install-kernel", line 131, in <module>
    with open("/var/tmp/reboot_needed", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/tmp/reboot_needed'
Traceback (most recent call last):
  File "/usr/bin/modify-cmdline", line 105, in <module>
    bash(f"sudo /usr/lib/eupnea/install-kernel --kernel-flags {temp_cmdline_file}")
  File "/usr/lib/eupnea/functions.py", line 117, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo /usr/lib/eupnea/install-kernel --kernel-flags /tmp/tmp.7x3ldZLZgE' returned non-zero exit status 1.
[corn@casta ~]$

(due to a glitch, github was not able to output my text into code, even if i set it)

**Comment by Apacelus** [comment]
/var/tmp is read-only...? Huh?
Which distro is this?

**Comment by cornflakes6374** [comment]
> /var/tmp is read-only...? Huh? Which distro is this?

Arch LInux

**Comment by WeirdTreeThing** [comment]
On my real Arch Linux system /var/tmp is writable.

**Comment by cornflakes6374** [comment]
> On my real Arch Linux system /var/tmp is writable.

does that mean i have to remount /var/tmp as read write?

**Comment by WeirdTreeThing** [comment]
/var/tmp is not a mountpoint.

**Comment by WeirdTreeThing** [comment]
On my system /var/tmp has full permissions for everyone and has the sticky permission.

**Comment by cornflakes6374** [comment]
> /var/tmp is not a mountpoint.

i had to remount /tmp and not /var/tmp to fix that.
```
[corn@casta ~]$ sudo mount -o remount,rw /tmp
[sudo] password for corn: 
[corn@casta ~]$ sudo mount -o remount,rw /tmp
[corn@casta ~]$ modify-cmdline

** (gedit:2323): WARNING **: 11:06:20.897: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.899: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.900: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.901: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.902: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.904: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.904: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.904: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.905: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (gedit:2323): WARNING **: 11:06:20.905: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory


New cmdline:
console= root=PARTUUID=bf39011e-ad94-4d63-bda2-cc934cf2ce3b i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1 intel_iommu=on enable_gvt=1 i915.enable_guc=0
Press ENTER to continue or CTRL+C to cancel
Backing up kernel
Backing up kernel requires root privileges.
131072+0 records in
131072+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 15.8635 s, 4.2 MB/s
Installing new kernel
Installing kernel requires root privileges.
131072+0 records in
131072+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 1.1524 s, 58.2 MB/s
78720+0 records in
78720+0 records out
40304640 bytes (40 MB, 38 MiB) copied, 8.06472 s, 5.0 MB/s
Kernel cmdline modified successfully! Please reboot to use the new cmdline
Press ENTER to reboot or CTRL+C to cancel reboot

```

**Comment by WeirdTreeThing** [comment]
I have no clue how that fixed it for you.

**Comment by WeirdTreeThing** [comment]
On my system /tmp and /var/tmp are two different folders.

**Comment by Apacelus** [comment]
@cornflakes6374 did you severely modify your systems setup?

**Comment by cornflakes6374** [comment]
> @cornflakes6374 did you severely modify your systems setup?

no
