### ISSUE TITLE
[BUG] fedora will not boot because of a systemd error

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#76]
**Describe the bug**
When booting fedora, (no matter if its desktop or cli) the system says failed to mount early api filesystems systemd freezing execution
here is the output of fsck on the sdcard:
```
chronos@localhost / $ sudo fsck -F /dev/sda3
fsck from util-linux 2.38.1
e2fsck 1.46.5 (30-Dec-2021)
/dev/sda3: clean, 58584/131072 files, 391756/503423 blocks
chronos@localhost / $ 
```
**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select fedora 38 as distro
3. Select CLI or desktop environment
4. build image, etch it and boot system

**Full log**

Verbose log:

**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
Chromeos (built on crouton on Samsung chromebook 4 (casta,bluebird,octopus)
**Additional context**

**Comment by cornflakes6374** [comment]
Arch Linux and other distros boot fine without error.

**Comment by cornflakes6374** [comment]
im trying fedora 39 instead to see if it works, please wait,

**Comment by cornflakes6374** [comment]
good news! i got it booted! Here's how:
1. mount the sdcard/usb with fedora installed into a folder in the downloads directory.
2. chroot into the folder with the sdcard mounted (requires sudo)
3. edit /etc/sysconfig/selinux, replace the line that has `SELINUX=enforcing` to `SELINUX=disabled`
4. exit the chroot, umount the folder, then reboot, then in the os verification is of screen, press CTRL-U
5. enjoy fedora!

**Comment by Apacelus** [comment]
1. Thats a very bad solution
2. The builder shouldve automatically relabeled all files for SELinux...
