### ISSUE TITLE
[BUG]  Could not boot USB stick

### ISSUE THREAD

**Issue by pazza2234** [eupnea-linux/depthboot-builder#77]
**Describe the bug**

I have a problem, where I can not run this command ```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0``` with out it either giving the error ```/usr/bin/crossystem: line 170: warning: /mnt/stateful_partition/mwtrollinggoogleforfakemurk:  warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md``` or, after I remounted /mnt/stateful_partition with exec, and executed it it looked fine but gave me a error when I pressed ctrl + u that I have not enabled USB boot. 

I think this is a problem with fake-murk or murk-mod, but I do not no how to remove murk-mod without fake-murk, or how to proceed. I will be resetting my Chromebook if I need to but I would like to make sure that I cant just, like do something stupid (I'm a skid obviously) to fix this.

**To Reproduce**

*note My Chromebook is [fakemurked](https://github.com/MercuryWorkshop/fakemurk) and has [murkmod](https://github.com/rainestorme/murkmod)*

1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select pop os as distro
3. Select (did not give potion) as desktop environment
4. go to Chromebook, open shell and type ```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0```
5. have it fail, and run ```mount -o remount,exec /mnt/stateful_partition```
6. run step 4 again
7. reboot to the Dev mode screen where you normally press ctrl + d
8. it gives you a error code in the top left of the screen wile the image stays there... and the error code ```warning: booting from external media (USB/SD) has not bin enabled```

**Build system (please complete the following information):**
 - OS: pop os

**Additional context**
- My Chromebook is the dell 3100, and is on the octopus board.
- The USB Stick is a MemoreX 64GB USB 3.1, but I did also try a USB 2.0 USB stick and got the same results.
- I am stupid so I might ask a few dumb questions sorry.
- It is on chrome OS 107.
- Root verification is off.
- I might enable it if it is a solution, but I do not got legacy bios enabled.
- I am not using ctrl + c and ctrl + v to type this, so it may not be 100% accurate but I typed as well as I could. It all looks right. Sorry if I missed type something.

**Comment by Apacelus** [comment]
Isnt that an issue for murk/fakemurk?

Crosssystem is a chromeos util

**Comment by pazza2234** [comment]
@Apacelus yes, I guess. I just don't know where exactly to go for the  issue report I guess. I followed the tutorial on  [eupnea-linux io page](https://eupnea-linux.github.io/). and I don't know if I should issue a problem on fake-murk repo because it could be a murk-mod problem, and murk-mod specify don't make issues on fakemurk repo, and it also is not a bug in either of them because its not there program doing it, but it might... idk sorry. but if you do know a solution let me know. closing the issue. I am probably going to reset my Chromebook.

**Comment by Apacelus** [comment]
I would make an issue on one of the repos with a title like "unable to use crosssystem"

**Comment by pazza2234** [comment]
@Apacelus ok! thanks that is a good idea!
