### ISSUE TITLE
[BUG] ubuntu is very jambled (broken textures in GNOME) and dpkg list files are very corrupt

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#79]
**Describe the bug**
The textures in gnome is very jambled as the apps icon is missing and window dialogs are transparent and also i tried to chroot to my ubuntu install in chrome os and dpkg lists files is broken (i written the image with dd)
`oot@localhost:/# apt install --reinstall x11-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 2 not upgraded.
Need to get 0 B/206 kB of archives.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
dpkg: warning: files list file for package 'xdg-desktop-portal-gtk' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libbasicobjects0:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-qxl' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'yaru-theme-gtk' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'usb-creator-gtk' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-amdgpu' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xdg-desktop-portal-gnome' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libauthen-sasl-perl' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-nouveau' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libxcb-keysyms1:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-ati' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libxcb-render-util0:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-radeon' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xcvt' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xorg-docs-core' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-fbdev' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-intel' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'wamerican' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-all' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'yaru-theme-icon' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xserver-xorg-video-vesa' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'x11-utils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xbitmaps' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xfonts-scalable' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'xcursor-themes' missing; assuming package has no files currently installed
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'xinit' is missing final newline
 
E: Sub-process /usr/bin/dpkg returned an error code (2)
root@localhost:/# 
root@localhost:/# `
**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select ubuntu as distro
3. Select GNOME as desktop environment
4. (optional) chroot into the sd card by creating a folder, mounting the sd card to the created folder, then chroot it.

**Full log**

Verbose log:

**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
ChromeOS on Samsung chromebook 4 (casta,octopus,bluebird) Image built with crouton and etched with dd
**Additional context**

**Comment by cornflakes6374** [comment]
![20230519_155011_HDR](https://github.com/eupnea-linux/depthboot-builder/assets/116115140/c4dd26a9-b5d5-4b41-b921-1a794dbd3f55)

**Comment by cornflakes6374** [comment]
Apps are also not opening and here is dialog box:
![20230519_155320](https://github.com/eupnea-linux/depthboot-builder/assets/116115140/2583728a-be83-42d1-b323-b942949645b9)

**Comment by Apacelus** [comment]
I unfortunately cannot replicate on fresh builds of ubuntu 22.04 and 23.04, both with gnome. Try making a new image?

**Comment by cornflakes6374** [comment]
i was able to fix broken textures with chrome recovery utility for disk writing instead of dd, but the dpkg file lists are still broken (corrupted)

**Comment by Apacelus** [comment]
Is that with the same image or a fresh one?

**Comment by cornflakes6374** [comment]
Same one, but then, after building with new image, the list files was working fine and everything was truly normal.
Closed
