### ISSUE TITLE
How to deal with this?

### ISSUE THREAD

**Issue by Infinite-Unexpired-Love** [eupnea-linux/depthboot-builder#86]
W: GPG error: https://storage.googleapis.com/cros-packages/98 bullseye Release: The following signatures were invalid: EXPKEYSIG 78BD65473CB3BD13 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
E: The repository 'https://storage.googleapis.com/cros-packages/98 bullseye Release' is not signed.
Traceback (most recent call last):
  File "/home/unexpiredbeloved/depthboot-builder/./main.py", line 104, in <module>
    bash("which pv xz parted cgpt futility")
  File "/home/unexpiredbeloved/depthboot-builder/functions.py", line 117, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'which pv xz parted cgpt futility' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/unexpiredbeloved/depthboot-builder/./main.py", line 125, in <module>
    bash("apt-get update -y")  # sync repos
  File "/home/unexpiredbeloved/depthboot-builder/functions.py", line 117, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'apt-get update -y' returned non-zero exit status 100.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options

**Comment by Infinite-Unexpired-Love** [comment]
now,the issue is:
Traceback (most recent call last):
  File "/home/unexpiredbeloved/depthboot-builder/./main.py", line 311, in <module>
    build.start_build(build_options=user_input, args=args)
  File "/home/unexpiredbeloved/depthboot-builder/build.py", line 478, in start_build
    download_rootfs(build_options["distro_name"], build_options["distro_version"])
  File "/home/unexpiredbeloved/depthboot-builder/build.py", line 55, in download_rootfs
    download_file(f"https://github.com/eupnea-linux/{distro_name}-rootfs/releases/latest/download/"
  File "/home/unexpiredbeloved/depthboot-builder/functions.py", line 303, in download_file
    urlretrieve(url=url, filename=path)
  File "/usr/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by Infinite-Unexpired-Love** [comment]
Is there anyway to use a proxy?

**Comment by Infinite-Unexpired-Love** [comment]
Now I use wsl2 to download the sys img.After that I plug the usb to my cb,only to see nothing(not a black screen,like booting ChromeOS waiting for the logo to occur).During the download,I got this err:
/sbin/setfiles: Could not set context for /dev/pts:  Operation not supported
Error connecting to audit system.
find: invalid predicate -context: SELinux is not enabled.
find: invalid predicate -context: SELinux is not enabled.
find: invalid predicate -context: SELinux is not enabled.
find: invalid predicate -context: SELinux is not enabled.
But in the end,the script told me a bootable img has done.What should I do?

**Comment by cornflakes6374** [comment]
> Now I use wsl2 to download the sys img.After that I plug the usb to my cb,only to see nothing(not a black screen,like booting ChromeOS waiting for the logo to occur).During the download,I got this err: /sbin/setfiles: Could not set context for /dev/pts: Operation not supported Error connecting to audit system. find: invalid predicate -context: SELinux is not enabled. find: invalid predicate -context: SELinux is not enabled. find: invalid predicate -context: SELinux is not enabled. find: invalid predicate -context: SELinux is not enabled. But in the end,the script told me a bootable img has done.What should I do?

if you said your img has been finished building, write the img to SD Card/USB Stick with `dd` or Chrome Recovery Utility (If using Chrome Recovery Utility, rename the .img to .bin)

**Comment by Infinite-Unexpired-Love** [comment]
Generally speaking, how long does it take to see the logo after inserting the USB flash drive (I once waited for half an hour but still couldn't wait for the results, the USB flash drive was so hot that I was afraid that it would burn out. I think my CB is not weak, it has the i31215U, 8GB, but it is an engineering machine)

**Comment by Infinite-Unexpired-Love** [comment]
boardName is GIMBLE-PVHI

**Comment by QuantumChilipepper** [comment]
I think right now there is not a boot logo but you should see the login screen or signs it is successfully booting up fairly quickly. Even on very slow devices I would say you should see something within a few minutes

**Comment by Infinite-Unexpired-Love** [comment]
I tried the ChromeOS kernel, and thankfully it worked, thanks to the developers' efforts. But now I'm still confused: the screen won't go off after shutting down, and you have to force it off. And I can't connect to wifi because there is no Wi-Fi option in the settings, and iwconfig tells me that I don't have a network card。
Using Ubuntu22.04 with Gnome。

**Comment by Infinite-Unexpired-Love** [comment]
> I tried the ChromeOS kernel, and thankfully it worked, thanks to the developers' efforts. But now I'm still confused: the screen won't go off after shutting down, and you have to force it off. And I can't connect to wifi because there is no Wi-Fi option in the settings, and iwconfig tells me that I don't have a network card。 Using Ubuntu22.04 with Gnome。
I found that this wireless card is supported above kernel 5.12, but the kernel installed by default is 5.10, can I update the kernel?

**Comment by Infinite-Unexpired-Love** [comment]
> I tried the ChromeOS kernel, and thankfully it worked, thanks to the developers' efforts. But now I'm still confused: the screen won't go off after shutting down, and you have to force it off. And I can't connect to wifi because there is no Wi-Fi option in the settings, and iwconfig tells me that I don't have a network card。 Using Ubuntu22.04 with Gnome。

I found that this wireless card is supported above kernel 5.12, but the kernel installed by default is 5.10, can I update the kernel?

**Comment by QuantumChilipepper** [comment]
It sounds like your device will need the mainline kernel for all the drivers to work correctly. I am working on a new release for the mainline kernel. Once that is finished you can use that and everything should work correctly.

**Comment by Infinite-Unexpired-Love** [comment]
Sadly it not support mainline kernel

**Comment by Infinite-Unexpired-Love** [comment]
What happens if I install kernel5.15 on the command line? I've tried installing the mainline kernel, and Ubuntu won't boot after rebooting.
